### PR TITLE
Slate

### PR DESCRIPTION
**Pull request by ajb**
cf #2 

Todo:

- [x] Use real-er cURL example (https://github.com/dobtco/screendoor-api-docs/pull/8#issuecomment-96661065)
- [x] Use partials for resource examples 
- [x] Proof / fill-in missing param descriptions
- [x] Deployment (@ajb)
- [x] Test suite? Link checker or something? (@ajb)

### CODE REVIEW

**Comment by kariannemah** [comment]
For the hash passed through "Update a response" curl command: shouldn't the key `response_fields` be `responses` as it is in the example `Response`? 
e13ke

**Comment by kariannemah** [comment]
> Only show one example of each resource (https://github.com/dobtco/screendoor-api-docs/pull/8#issuecomment-96661065)

I went back and forth on this, but I think we should include an example response for each method as Stripe does. It's a lot clearer. Better to err on the side of redundancy than opacity.

**Comment by ajb** [comment]
Works for me if we can figure out the correct way to include a partial.

On Wed, Apr 29, 2015 at 3:29 AM, Kari Mah <notifications@github.com> wrote:

> Only show one example of each resource (#8 (comment)
> <https://github.com/dobtco/screendoor-api-docs/pull/8#issuecomment-96661065>
> )
>
> I went back and forth on this, but I think we should include an example
> response for each method as Stripe does. It's a lot clearer. Better to err
> on the side of redundancy than opacity.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/screendoor-api-docs/pull/10#issuecomment-97331482>
> .
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by kariannemah** [comment]
Okay, I'll look into partials. I'm using comments as headings (e.g., #
Example Response) in the interim.

**Comment by ajb** [comment]
Updated with Middleman partial syntax and other fixes.

@kariannemah this should be good to merge... lmk when you do and I'll make sure it deploys properly.

**Comment by ajb** [comment]
Gonna merge this!

**Pull request merged**
